/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* /home/charlie/lscc/diamond/3.14/ispfpga/bin/lin64/scuba -w -n fifo -lang verilog -synth lse -bus_exp 7 -bl -arch xo2c00 -type ebfifo -depth 2048 -width 16 -rwidth 32 -no_enable -pe 10 -pf 1024  */
/* Wed Jan 28 13:21:58 2026 */


`timescale 1 ns / 1 ps
module fifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [0:15] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [0:31] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    defparam fifo_0_3.FULLPOINTER1 = "0b01111111111000" ;
    defparam fifo_0_3.FULLPOINTER = "0b10000000000000" ;
    defparam fifo_0_3.AFPOINTER1 = "0b00111111111000" ;
    defparam fifo_0_3.AFPOINTER = "0b01000000000000" ;
    defparam fifo_0_3.AEPOINTER1 = "0b00000001011000" ;
    defparam fifo_0_3.AEPOINTER = "0b00000001010000" ;
    defparam fifo_0_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_0_3.GSR = "DISABLED" ;
    defparam fifo_0_3.RESETMODE = "ASYNC" ;
    defparam fifo_0_3.REGMODE = "NOREG" ;
    defparam fifo_0_3.CSDECODE_R = "0b11" ;
    defparam fifo_0_3.CSDECODE_W = "0b11" ;
    defparam fifo_0_3.DATA_WIDTH_R = 9 ;
    defparam fifo_0_3.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_0_3 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), .DI3(Data[3]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), .DO1(Q[1]), .DO2(Q[2]), 
        .DO3(Q[3]), .DO4(Q[16]), .DO5(Q[17]), .DO6(Q[18]), .DO7(Q[19]), 
        .DO8(), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), 
        .DO16(), .DO17(), .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), 
        .FF(Full_int));

    defparam fifo_1_2.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_2.FULLPOINTER = "0b11111111111000" ;
    defparam fifo_1_2.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_2.AFPOINTER = "0b11111111111000" ;
    defparam fifo_1_2.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_2.AEPOINTER = "0b11111111111000" ;
    defparam fifo_1_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_1_2.GSR = "DISABLED" ;
    defparam fifo_1_2.RESETMODE = "ASYNC" ;
    defparam fifo_1_2.REGMODE = "NOREG" ;
    defparam fifo_1_2.CSDECODE_R = "0b11" ;
    defparam fifo_1_2.CSDECODE_W = "0b11" ;
    defparam fifo_1_2.DATA_WIDTH_R = 9 ;
    defparam fifo_1_2.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_1_2 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), .DI3(Data[7]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[4]), .DO1(Q[5]), .DO2(Q[6]), 
        .DO3(Q[7]), .DO4(Q[20]), .DO5(Q[21]), .DO6(Q[22]), .DO7(Q[23]), 
        .DO8(), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), 
        .DO16(), .DO17(), .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_2_1.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_1.FULLPOINTER = "0b11111111111000" ;
    defparam fifo_2_1.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_1.AFPOINTER = "0b11111111111000" ;
    defparam fifo_2_1.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_1.AEPOINTER = "0b11111111111000" ;
    defparam fifo_2_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_2_1.GSR = "DISABLED" ;
    defparam fifo_2_1.RESETMODE = "ASYNC" ;
    defparam fifo_2_1.REGMODE = "NOREG" ;
    defparam fifo_2_1.CSDECODE_R = "0b11" ;
    defparam fifo_2_1.CSDECODE_W = "0b11" ;
    defparam fifo_2_1.DATA_WIDTH_R = 9 ;
    defparam fifo_2_1.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_2_1 (.DI0(Data[8]), .DI1(Data[9]), .DI2(Data[10]), .DI3(Data[11]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[8]), .DO1(Q[9]), .DO2(Q[10]), 
        .DO3(Q[11]), .DO4(Q[24]), .DO5(Q[25]), .DO6(Q[26]), .DO7(Q[27]), 
        .DO8(), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), 
        .DO16(), .DO17(), .EF(), .AEF(), .AFF(), .FF());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam fifo_3_0.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_0.FULLPOINTER = "0b11111111111000" ;
    defparam fifo_3_0.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_0.AFPOINTER = "0b11111111111000" ;
    defparam fifo_3_0.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_0.AEPOINTER = "0b11111111111000" ;
    defparam fifo_3_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_3_0.GSR = "DISABLED" ;
    defparam fifo_3_0.RESETMODE = "ASYNC" ;
    defparam fifo_3_0.REGMODE = "NOREG" ;
    defparam fifo_3_0.CSDECODE_R = "0b11" ;
    defparam fifo_3_0.CSDECODE_W = "0b11" ;
    defparam fifo_3_0.DATA_WIDTH_R = 9 ;
    defparam fifo_3_0.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_3_0 (.DI0(Data[12]), .DI1(Data[13]), .DI2(Data[14]), .DI3(Data[15]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[12]), .DO1(Q[13]), .DO2(Q[14]), 
        .DO3(Q[15]), .DO4(Q[28]), .DO5(Q[29]), .DO6(Q[30]), .DO7(Q[31]), 
        .DO8(), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), 
        .DO16(), .DO17(), .EF(), .AEF(), .AFF(), .FF());

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar end

endmodule
