/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* /home/charlie/lscc/diamond/3.14/ispfpga/bin/lin64/scuba -w -n fifo -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type ebfifo -depth 1024 -width 32 -rwidth 32 -regout -resetmode SYNC -no_enable -pe 10 -pf 520 -sync_reset  */
/* Thu Mar 26 23:41:47 2026 */


`timescale 1 ns / 1 ps
module fifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [31:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [31:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire Empty_int;
    wire Full_int;
    wire scuba_vhi;
    wire scuba_vlo;

    defparam fifo_0_3.FULLPOINTER1 = "0b01111111111000" ;
    defparam fifo_0_3.FULLPOINTER = "0b10000000000000" ;
    defparam fifo_0_3.AFPOINTER1 = "0b01000000111000" ;
    defparam fifo_0_3.AFPOINTER = "0b01000001000000" ;
    defparam fifo_0_3.AEPOINTER1 = "0b00000001011000" ;
    defparam fifo_0_3.AEPOINTER = "0b00000001010000" ;
    defparam fifo_0_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_0_3.GSR = "DISABLED" ;
    defparam fifo_0_3.RESETMODE = "SYNC" ;
    defparam fifo_0_3.REGMODE = "OUTREG" ;
    defparam fifo_0_3.CSDECODE_R = "0b11" ;
    defparam fifo_0_3.CSDECODE_W = "0b11" ;
    defparam fifo_0_3.DATA_WIDTH_R = 9 ;
    defparam fifo_0_3.DATA_WIDTH_W = 9 ;
    FIFO8KB fifo_0_3 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), .DI3(Data[3]), 
        .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), .DI8(Data[8]), 
        .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), .DI12(scuba_vlo), 
        .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), .DI16(scuba_vlo), 
        .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), .CSR0(RdEn), 
        .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), .WE(WrEn), 
        .RE(scuba_vhi), .ORE(scuba_vhi), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), .DO1(Q[1]), .DO2(Q[2]), 
        .DO3(Q[3]), .DO4(Q[4]), .DO5(Q[5]), .DO6(Q[6]), .DO7(Q[7]), .DO8(Q[8]), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int));

    defparam fifo_1_2.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_2.FULLPOINTER = "0b11111111111000" ;
    defparam fifo_1_2.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_2.AFPOINTER = "0b11111111111000" ;
    defparam fifo_1_2.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_2.AEPOINTER = "0b11111111111000" ;
    defparam fifo_1_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_1_2.GSR = "DISABLED" ;
    defparam fifo_1_2.RESETMODE = "SYNC" ;
    defparam fifo_1_2.REGMODE = "OUTREG" ;
    defparam fifo_1_2.CSDECODE_R = "0b11" ;
    defparam fifo_1_2.CSDECODE_W = "0b11" ;
    defparam fifo_1_2.DATA_WIDTH_R = 9 ;
    defparam fifo_1_2.DATA_WIDTH_W = 9 ;
    FIFO8KB fifo_1_2 (.DI0(Data[9]), .DI1(Data[10]), .DI2(Data[11]), .DI3(Data[12]), 
        .DI4(Data[13]), .DI5(Data[14]), .DI6(Data[15]), .DI7(Data[16]), 
        .DI8(Data[17]), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[9]), .DO1(Q[10]), .DO2(Q[11]), 
        .DO3(Q[12]), .DO4(Q[13]), .DO5(Q[14]), .DO6(Q[15]), .DO7(Q[16]), 
        .DO8(Q[17]), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), 
        .DO15(), .DO16(), .DO17(), .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_2_1.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_1.FULLPOINTER = "0b11111111111000" ;
    defparam fifo_2_1.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_1.AFPOINTER = "0b11111111111000" ;
    defparam fifo_2_1.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_1.AEPOINTER = "0b11111111111000" ;
    defparam fifo_2_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_2_1.GSR = "DISABLED" ;
    defparam fifo_2_1.RESETMODE = "SYNC" ;
    defparam fifo_2_1.REGMODE = "OUTREG" ;
    defparam fifo_2_1.CSDECODE_R = "0b11" ;
    defparam fifo_2_1.CSDECODE_W = "0b11" ;
    defparam fifo_2_1.DATA_WIDTH_R = 9 ;
    defparam fifo_2_1.DATA_WIDTH_W = 9 ;
    FIFO8KB fifo_2_1 (.DI0(Data[18]), .DI1(Data[19]), .DI2(Data[20]), .DI3(Data[21]), 
        .DI4(Data[22]), .DI5(Data[23]), .DI6(Data[24]), .DI7(Data[25]), 
        .DI8(Data[26]), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[18]), .DO1(Q[19]), .DO2(Q[20]), 
        .DO3(Q[21]), .DO4(Q[22]), .DO5(Q[23]), .DO6(Q[24]), .DO7(Q[25]), 
        .DO8(Q[26]), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), 
        .DO15(), .DO16(), .DO17(), .EF(), .AEF(), .AFF(), .FF());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam fifo_3_0.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_0.FULLPOINTER = "0b11111111111000" ;
    defparam fifo_3_0.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_0.AFPOINTER = "0b11111111111000" ;
    defparam fifo_3_0.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_0.AEPOINTER = "0b11111111111000" ;
    defparam fifo_3_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_3_0.GSR = "DISABLED" ;
    defparam fifo_3_0.RESETMODE = "SYNC" ;
    defparam fifo_3_0.REGMODE = "OUTREG" ;
    defparam fifo_3_0.CSDECODE_R = "0b11" ;
    defparam fifo_3_0.CSDECODE_W = "0b11" ;
    defparam fifo_3_0.DATA_WIDTH_R = 9 ;
    defparam fifo_3_0.DATA_WIDTH_W = 9 ;
    FIFO8KB fifo_3_0 (.DI0(Data[27]), .DI1(Data[28]), .DI2(Data[29]), .DI3(Data[30]), 
        .DI4(Data[31]), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[27]), .DO1(Q[28]), .DO2(Q[29]), 
        .DO3(Q[30]), .DO4(Q[31]), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar end

endmodule
