/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Thu Mar 26 16:47:36 2026 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
