/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Tue Mar 24 01:02:01 2026 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
