/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sat Mar 28 23:07:12 2026 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
