/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 7.5 */
/* Sun Mar 22 18:20:46 2026 */

/* parameterized module instance */
ram __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), .Data( ), 
    .Q( ));
