[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 1;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = htclk_c;
GLOBAL_PRIMARY_0_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_0_LOADNUM = 150;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 4;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = htclk_c_enable_114;
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 20;
GLOBAL_SECONDARY_0_SIGTYPE = CE+RST;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = counter_0;
GLOBAL_SECONDARY_1_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_1_LOADNUM = 26;
GLOBAL_SECONDARY_1_SIGTYPE = CE+RST;
; Global secondary clock #2
GLOBAL_SECONDARY_2_SIGNALNAME = htclk_c_enable_103;
GLOBAL_SECONDARY_2_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_2_LOADNUM = 32;
GLOBAL_SECONDARY_2_SIGTYPE = CE;
; Global secondary clock #3
GLOBAL_SECONDARY_3_SIGNALNAME = htclk_c_enable_72;
GLOBAL_SECONDARY_3_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_3_LOADNUM = 16;
GLOBAL_SECONDARY_3_SIGTYPE = CE;
; I/O Bank 0 Usage
BANK_0_USED = 14;
BANK_0_AVAIL = 19;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 21;
BANK_1_AVAIL = 21;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 14;
BANK_2_AVAIL = 20;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 20;
BANK_3_AVAIL = 20;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
